[package]
name = "universe"
version = "0.1.0"
authors = ["Marco Buono <thecoreh@gmail.com>"]
build = "build.rs"

[dependencies]
quick-error = "1.2.0"
sdl2 = "0.30.0"
gl = "0.6.0"

[features]
default = ["opengl"]
opengl = []
